# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: 
           em: '@doctrine.orm.entity_manager'
           pe: '@security.password_encoder'
           ts: '@security.token_storage'
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
