<?php

namespace StoreBundle\Repository;

/**
 * ParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamsRepository extends \Doctrine\ORM\EntityRepository
{
}
